### PR TITLE
Update README.md with new reference

### PR DESCRIPTION
**Pull request by ChildishGirl**
# Thanks for your help

## However, please check if the PR fulfills these requirements

1. [ ] Links are correct
2. [ ] Github handle of user is specify,
if not use LinkedIn link, or Twitter
3. [ ] Spellcheck is enabled, in case of GH Action errors
with usernames edit `.wordlist.txt`, however fix typos
4. [ ] Entry is according to standard

    ```markdown
    - [Name](URL) - Resources description [@github-username](https://github.com/github-username)
    ```

### CODE REVIEW

**Comment by 3sky** [comment]
Hi @ChildishGirl, seems like you need to fix your commit a bit!

**Comment by ChildishGirl** [comment]
Hey @3sky, seems like"Curate all links" check hasn't passed due to some other error, not related to my content:
```
ERROR: 1 dead links found!
[✖] https://www.youtube.com/@lastweekinit → Status: 404
```

Meanwhile, I changed length of the lines and added words to dictionary for spelling check.

**Comment by 3sky** [comment]
Sounds fair, probably you can delete this entity for now. And still, some trailing spaces exists ;) 

btw, @pawelpiwosz please bring your channel to live 🙂

**Comment by ChildishGirl** [comment]
@3sky, deleted both trailing spaces and broken link. Hopefully, this time everything will be fine 🤞🏻

**Review by 3sky — APPROVED** [review]
lgtm

**Comment by 3sky** [comment]
Congratulations @ChildishGirl it working! Thanks for your contribution.

**Pull request merged**
