### PR TITLE
Add Learning Paths for AWS Graviton processors and fix spelling errors

### PR DESCRIPTION
**Pull request by jasonrandrews**
# Thanks for your help

## However, please check if the PR fulfills these requirements

1. [x] Links are correct
2. [x] Github handle of user is specify, if not use LinkedIn link
3. [x] Entry is according to standard

    ```markdown
    - [Name](URL) - Resources description [@github-username](https://github.com/github-username)
    ```

### CODE REVIEW

**Review by 3sky — APPROVED** [review]

**Comment by 3sky** [comment]
Hi @jasonrandrews, please lint your markdown. Thanks!

**Comment by 3sky** [comment]
Also based on your input I added spellcheck to the project, thanks for the idea!

**Comment by 3sky** [comment]
Hi, as "Graviton" is not a `regular` word, but product's name adjustment in .wordlists.txt is needed.

**Comment by jasonrandrews** [comment]
I have added Graviton to the spell check word list.

**Comment by 3sky** [comment]
Thanks @jasonrandrews for contributing, as well as for all fixtures over the time!

**Pull request merged**
