### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iammukeshm**
# Thanks for your help

## However, please check if the PR fulfills these requirements

1. [x] Links are correct
2. [x] Github handle of user is specify,
if not use LinkedIn link, or Twitter
3. [x] Spellcheck is enabled, in case of GH Action errors
with usernames edit `.wordlist.txt`, however fix typos
4. [x] Entry is according to standard

    ```markdown
    - [Name](URL) - Resources description [@github-username](https://github.com/github-username)
    ```

### CODE REVIEW

**Comment by 3sky** [comment]
Hi @iammukeshm, some improvements are needed.

**Comment by iammukeshm** [comment]
> Hi @iammukeshm, some improvements are needed.

What all do you want me to change? @3sky

**Comment by 3sky** [comment]
Hello again, as you can see Spellcheck is falling, you need to add "new" words to:
https://github.com/3sky/awscb-content-catalog/blob/main/.wordlist.txt

**Comment by iammukeshm** [comment]
> Hello again, as you can see Spellcheck is falling, you need to add "new" words to: https://github.com/3sky/awscb-content-catalog/blob/main/.wordlist.txt

done, all are passing now

**Review by 3sky — APPROVED** [review]

**Comment by 3sky** [comment]
Thanks @iammukeshm for your contribution!

**Pull request merged**
